=== bdatdo0601/big-boi/amplify/backend/function/bigboibigboilambdalayer/opt/schema/message.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "The root schema",
  "description": "The root schema comprises the entire JSON document.",
  "default": {},
  "examples": [
    {
      "id": "6293d2b3-5fde-4bf0-8b69-14734283f7bd",
      "sourceID": "shardId-000000000000:49620770030960603994186530106341665232583331965449535490",
      "source": "aws:kinesis:record",
      "eventType": "Personal.BlogPost.Update",
      "content": {},
      "metadata": {
        "timestamp": 112904812049,
        "sourceURI": "arn:aws:kinesis:us-east-1:142037127835:stream/bigboidefaultkinesis-dev"
      },
      "publishInfo": {
        "subject": "Dat",
        "subjectLink": "https://www.dat.do",
        "action": "just updated",
        "target": "his blog post",
        "targetLink": "https://www.test.com/",
        "message": "Dat just updated his blog post"
      }
    }
  ],
  "required": ["id", "sourceID", "source", "eventType", "content", "metadata", "publishInfo"],
  "properties": {
    "id": {
      "$id": "#/properties/id",
      "type": "string",
      "title": "The id schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["6293d2b3-5fde-4bf0-8b69-14734283f7bd"]
    },
    "sourceID": {
      "$id": "#/properties/sourceID",
      "type": "string",
      "title": "The sourceID schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["shardId-000000000000:49620770030960603994186530106341665232583331965449535490"]
    },
    "source": {
      "$id": "#/properties/source",
      "type": "string",
      "title": "The source schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["aws:kinesis:record"]
    },
    "eventType": {
      "$id": "#/properties/eventType",
      "type": "string",
      "title": "The eventType schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["Personal.BlogPost.Update"]
    },
    "content": {
      "$id": "#/properties/content",
      "type": "object",
      "title": "The content schema",
      "description": "An explanation about the purpose of this instance.",
      "default": {},
      "examples": [{}],
      "required": [],
      "additionalProperties": true
    },
    "metadata": {
      "$id": "#/properties/metadata",
      "type": "object",
      "title": "The metadata schema",
      "description": "An explanation about the purpose of this instance.",
      "default": {},
      "examples": [
        {
          "timestamp": 112904812049,
          "sourceURI": "arn:aws:kinesis:us-east-1:142037127835:stream/bigboidefaultkinesis-dev"
        }
      ],
      "required": ["timestamp", "sourceURI", "visibility", "sourceMessage"],
      "properties": {
        "timestamp": {
          "$id": "#/properties/metadata/properties/timestamp",
          "type": "integer",
          "title": "The timestamp schema",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [112904812049]
        },
        "sourceURI": {
          "$id": "#/properties/metadata/properties/sourceURI",
          "type": "string",
          "title": "The sourceURI schema",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": ["arn:aws:kinesis:us-east-1:142037127835:stream/bigboidefaultkinesis-dev"]
        },
        "visibility": {
          "$id": "#/properties/metadata/properties/visibility",
          "type": "string",
          "title": "Visibility",
          "description": "Whether it is intended to be seen in public",
          "default": "private",
          "examples": ["public", "private"]
        },
        "isValid": {
          "$id": "#/properties/metadata/properties/isValid",
          "type": "boolean",
          "title": "isValid",
          "description": "Whether the message can be consumed properly",
          "default": false,
          "examples": [true, false]
        },
        "sourceMessage": {
          "$id": "#/properties/metadata/properties/sourceMessage",
          "type": "object",
          "title": "sourceMessage",
          "description": "Raw message from the source",
          "default": {}
        }
      },
      "additionalProperties": true
    },
    "publishInfo": {
      "$id": "#/properties/publishInfo",
      "type": "object",
      "title": "The publishInfo schema",
      "description": "An explanation about the purpose of this instance.",
      "default": {},
      "examples": [
        {
          "subject": "Dat",
          "subjectLink": "https://www.dat.do",
          "action": "just updated",
          "target": "his blog post",
          "targetLink": "https://www.test.com/",
          "message": "Dat just updated his blog post"
        }
      ],
      "required": ["subject", "subjectLink", "action", "target", "targetLink", "message"],
      "properties": {
        "subject": {
          "$id": "#/properties/publishInfo/properties/subject",
          "type": "string",
          "title": "The subject schema",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": ["Dat"]
        },
        "subjectLink": {
          "$id": "#/properties/publishInfo/properties/subjectLink",
          "type": "string",
          "title": "The subjectLink schema",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": ["https://www.dat.do"]
        },
        "action": {
          "$id": "#/properties/publishInfo/properties/action",
          "type": "string",
          "title": "The action schema",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": ["just updated"]
        },
        "target": {
          "$id": "#/properties/publishInfo/properties/target",
          "type": "string",
          "title": "The target schema",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": ["his blog post"]
        },
        "targetLink": {
          "$id": "#/properties/publishInfo/properties/targetLink",
          "type": "string",
          "title": "The targetLink schema",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": ["https://www.test.com/"]
        },
        "message": {
          "$id": "#/properties/publishInfo/properties/message",
          "type": "string",
          "title": "The message schema",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": ["Dat just updated his blog post"]
        }
      },
      "additionalProperties": true
    }
  },
  "additionalProperties": true
}

=== bdatdo0601/big-boi/amplify/backend/function/bigboibigboilambdalayer/opt/example/message.json
{
  "id": "6293d2b3-5fde-4bf0-8b69-14734283f7bd",
  "sourceID": "shardId-000000000000:49620770030960603994186530106341665232583331965449535490",
  "source": "aws:kinesis:record",
  "eventType": "Personal.BlogPost.Update",
  "content": {},
  "metadata": {
    "timestamp": 112904812049,
    "sourceURI": "arn:aws:kinesis:us-east-1:142037127835:stream/bigboidefaultkinesis-dev",
    "visibility": "public",
    "sourceMessage": {},
    "additionalData": {},
    "isValid": false
  },
  "publishInfo": {
    "icon": {
      "type": "Icon",
      "value": "info"
    },
    "subject": "Dat",
    "subjectLink": "https://www.dat.do",
    "action": "just updated",
    "target": "his blog post",
    "targetLink": "https://www.test.com/",
    "message": "Dat just updated his blog post"
  }
}
